export const trades = [
    {
        userId: "69c6ac9b2cade7866dbbc6e8",
        title: "EUR/USD Breakout",
        tradeDate: "2026-03-27T09:30:00Z",
        pnl: 1500,
        duration: 60,
        tradeAmount: 20000,
        isProfit: "PROFIT",
        timeFrame: "5m",
        strategy: "SCALPING",
        notes: "Clean breakout, good entry",
        status: "PUBLISHED",
        mode: "FOREX"
    },
    {
        userId: "69c6ac9b2cade7866dbbc6e8",
        title: "GBP/USD Loss Trade",
        tradeDate: "2026-03-27T11:00:00Z",
        pnl: -700,
        duration: 30,
        tradeAmount: 15000,
        isProfit: "LOSS",
        timeFrame: "1m",
        strategy: "SCALPING",
        notes: "Late entry, quick reversal",
        status: "PUBLISHED",
        mode: "FOREX"
    },
    {
        userId: "69c6ac9b2cade7866dbbc6e8",
        title: "BankNifty Intraday",
        tradeDate: "2026-03-26T10:15:00Z",
        pnl: 2200,
        duration: 45,
        tradeAmount: 12000,
        isProfit: "PROFIT",
        timeFrame: "5m",
        strategy: "INTRADAY",
        notes: "Strong breakout above resistance",
        status: "PUBLISHED",
        mode: "INDIAN_STOCK",

    },
    {
        userId: "69c6ac9b2cade7866dbbc6e8",
        title: "Nifty Fake Breakout",
        tradeDate: "2026-03-26T12:00:00Z",
        pnl: -1200,
        duration: 50,
        tradeAmount: 10000,
        isProfit: "LOSS",
        timeFrame: "15m",
        strategy: "INTRADAY",
        notes: "Fake breakout, trapped",
        status: "PUBLISHED",
        mode: "INDIAN_STOCK"
    },
    {
        userId: "69c6ac9b2cade7866dbbc6e8",
        title: "USD/JPY Swing",
        tradeDate: "2026-03-24T08:00:00Z",
        pnl: 3500,
        duration: 1440,
        tradeAmount: 30000,
        isProfit: "PROFIT",
        timeFrame: "1D",
        strategy: "SWING",
        notes: "Trend continuation, held patiently",
        status: "PUBLISHED",
        mode: "FOREX",
        images: ["usdjpy.png"]
    },
    {
        userId: "69c6ac9b2cade7866dbbc6e8",
        title: "TCS Positional",
        tradeDate: "2026-03-20T09:00:00Z",
        pnl: 5000,
        duration: 4320,
        tradeAmount: 40000,
        isProfit: "PROFIT",
        timeFrame: "4H",
        strategy: "POSITIONAL",
        notes: "Breakout with strong trend",
        status: "PUBLISHED",
        mode: "INDIAN_STOCK"
    }
];